// project problem_002 main.go
// Solution for Project Euler Problem #102, Even Fibonacci numbers.
package main

import "fmt"

func main() {
	var j int
	i := 1
	var s int

	for n := i + j; n <= 4000000; n = j + i {
		if n%2 == 0 {
			s += n
		}
		fmt.Println(n, s)
		j = i
		i = n
	}
}

/*
 Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous
 two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
*/
